"""Add org_id to simulations

Revision ID: d4f776eb36ba
Revises: c9d4e5f6g7h8
Create Date: 2026-06-08 17:54:31.492922

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4f776eb36ba"
down_revision: Union[str, Sequence[str], None] = "c9d4e5f6g7h8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Keep external_data_cache
    pass
    with op.batch_alter_table("digital_twins", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("org_id", sa.Integer(), nullable=False, server_default="1")
        )
        batch_op.create_index(
            batch_op.f("ix_digital_twins_org_id"), ["org_id"], unique=False
        )
        # Foreign keys with SQLite alter table have limitations, but Alembic handles batch correctly
        # batch_op.create_foreign_key(None, 'organizations', ['org_id'], ['id'])

    with op.batch_alter_table("forecast_records", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("org_id", sa.Integer(), nullable=False, server_default="1")
        )
        batch_op.create_index(
            batch_op.f("ix_forecast_records_org_id"), ["org_id"], unique=False
        )
        # batch_op.create_foreign_key(None, 'organizations', ['org_id'], ['id'])

    with op.batch_alter_table("simulations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("org_id", sa.Integer(), nullable=False, server_default="1")
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.create_index(
            batch_op.f("ix_simulations_org_id"), ["org_id"], unique=False
        )
        # batch_op.create_foreign_key(None, 'organizations', ['org_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("simulations", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_simulations_org_id"))
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )
        batch_op.drop_column("org_id")

    with op.batch_alter_table("forecast_records", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_forecast_records_org_id"))
        batch_op.drop_column("org_id")

    with op.batch_alter_table("digital_twins", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_digital_twins_org_id"))
        batch_op.drop_column("org_id")

    # Keep external_data_cache in downgrade
    pass

    # ### end Alembic commands ###
